# Generated by Django 5.0.1 on 2024-03-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asesores', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='media/contratos/')),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diseno_CNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='media/disenoCNC/')),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diseno_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='media/disenoProduccion/')),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_de_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(blank=True, default='Esperando diseño CNC', null=True)),
                ('archivo', models.FileField(upload_to='media/Produccion/')),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diseno_CNC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_cnc')),
                ('diseno_produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_Entregado', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.FileField(upload_to='media/contratos/')),
                ('carta', models.FileField(upload_to='media/carta/')),
                ('hojaproduccion', models.ManyToManyField(blank=True, to='Produccion.hoja_de_produccion')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Asesores.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produccion.orden_trabajo')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produccion.trabajo')),
            ],
        ),
    ]
