# Generated by Django 5.0.1 on 2024-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja_de_produccion',
            name='estado',
            field=models.TextField(blank=True, default='Esperando diseño CNC', null=True),
        ),
    ]
