# Generated by Django 5.0.1 on 2024-04-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja_de_produccion',
            name='diseno_CNC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_cnc'),
        ),
        migrations.AlterField(
            model_name='hoja_de_produccion',
            name='diseno_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_produccion'),
        ),
    ]
