# Generated by Django 5.0.1 on 2024-02-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_trabajo',
            name='diseno_CNC',
        ),
        migrations.RemoveField(
            model_name='orden_trabajo',
            name='diseno_produccion',
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseno_produccion',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoja_de_produccion',
            name='diseno_CNC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_cnc'),
        ),
        migrations.AddField(
            model_name='hoja_de_produccion',
            name='diseno_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Produccion.diseno_produccion'),
        ),
        migrations.AddField(
            model_name='hoja_de_produccion',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
