# Generated by Django 5.0.1 on 2024-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno_cnc',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
