# Generated by Django 5.0.1 on 2024-02-14 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0003_trabajo_grup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_trabajo',
            name='fecha_Entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden_trabajo',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
