# Generated by Django 5.0.1 on 2024-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0004_orden_trabajo_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
