# Generated by Django 5.0.1 on 2024-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='estado',
        ),
        migrations.AlterField(
            model_name='diseno',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
