# Generated by Django 5.0.1 on 2024-01-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='necesita_diseño',
            field=models.BooleanField(default=False),
        ),
    ]
