# Generated by Django 5.0.1 on 2024-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='fecha_cambio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
