# Generated by Django 5.0.1 on 2024-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0002_diseno_necesita_diseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
