# Generated by Django 5.0.1 on 2024-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0002_remove_presupuesto_estado_alter_diseno_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cliente',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='descripcion',
            field=models.CharField(default='Pendiente', max_length=500),
        ),
    ]
