# Generated by Django 5.0.1 on 2024-01-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0002_alter_diseno_archivo'),
        ('Asesores', '0003_presupuesto_estado'),
    ]

    operations = [
    ]
