# Generated by Django 5.0.1 on 2024-01-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0003_presupuesto_cliente_presupuesto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
