# Generated by Django 5.0.1 on 2024-01-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0004_merge_20240129_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseno',
            name='necesita_diseño',
        ),
    ]
