# Generated by Django 5.0.1 on 2024-01-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0004_alter_presupuesto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
