# Generated by Django 5.0.1 on 2024-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0005_alter_presupuesto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
