# Generated by Django 5.0.1 on 2024-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0005_remove_diseno_necesita_diseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
