# Generated by Django 5.0.1 on 2024-02-02 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asesores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(blank=True, default='Esperando aprobación', null=True)),
                ('archivo', models.FileField(upload_to='cotizaciones/')),
                ('cotizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diseno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Asesores.diseno')),
            ],
        ),
    ]
