# Generated by Django 4.2.11 on 2024-03-06 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Asesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(blank=True, default='Esperando aprobación', null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='media/cotizaciones/')),
                ('cotizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diseno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Asesores.diseno')),
            ],
        ),
    ]
