# Generated by Django 5.0.1 on 2024-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='archivo',
            field=models.FileField(upload_to='cotizaciones/'),
        ),
    ]
