# Generated by Django 5.0.1 on 2024-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizadores', '0002_alter_cotizacion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
