# Generated by Django 5.0.1 on 2024-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizadores', '0003_cotizacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.TextField(blank=True, default='Esperando aprobación', null=True),
        ),
    ]
