# Generated by Django 5.0.1 on 2024-01-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesores', '0007_alter_diseno_estado'),
        ('Cotizadores', '0004_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='presupuesto',
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_reserva', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cotizadores.cotizacion')),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Asesores.diseno')),
            ],
        ),
    ]
